### ISSUE TITLE
Consistency

### ISSUE THREAD

**Issue by mturiansky** [WatsonGroupTCD/J2suscep#13]
[_review for JOSS_](https://github.com/openjournals/joss-reviews/issues/2838)

I've noticed several spelling errors throughout the output, which should be cleaned up. I also find the lack of consistency between the input file a bit inconvenient to use. For example, "J values" for ej_calc is the number of J values, while for suscep it is the actual list of J values. Why do you need "Hamiltonian Ends" in ej_calc but not in suscep?

On a separate note, is there a way to specify the temperature range or granularity for suscep? That seems like a desirable feature.

**Comment by mfherbst** [comment]
Related to that: Is it possible to configure the thresholds (e.g. the 1cm^{-1} used to identify generate spin states)? That would probably be handy as well.

**Comment by Swetanshu** [comment]
@mfherbst @mturiansky 
The spelling errors have been removed. 
The use of “J values” and “Hamiltonian Ends” has been made consistent now
The temperature range can be specified now in the input file.
Since the energy of different spin states are approximated here to begin with, one may determine the ground spin state and the spin of the highest energy state but it is not advisable to estimate degeneracies from this data. The threshold of 1 cm-1 was arbitrarily chosen to provide some spacing between the rows but should not be interpreted as the definition of degeneracy. To look at the degeneracies properly, one needs to diagonalise the entire matrix of Ms elements.

**Comment by mturiansky** [comment]
I'm okay with the changes that have been made. If @mfherbst is okay also, then this can be closed.

**Comment by mfherbst** [comment]
Me too.
